#:import colormap kivy.utils.colormap
#:import from_hex kivy.utils.get_color_from_hex

#:set main_color '#F3AF12'
#:set main_color_dark '#c9890e'

<ButtonMenu@Button>:
    font_size: '20sp'
    bold: True
    background_color: 0, 0, 0, 0
    size_hint: 1, None
    height: '60dp'
    canvas.before:
        Color:
            rgba: colormap['white']
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [dp(30)]
        Color:
            rgba: from_hex(main_color) if self.state == 'normal' else from_hex(main_color_dark)
        RoundedRectangle:
            size: self.size[0] - dp(6), self.size[1] - dp(6)
            pos: self.pos[0] + dp(3), self.pos[1] + dp(3)
            radius: [dp(30)]

<ButtonIcon@ButtonMenu>:
    font_name: 'assets/typicons.ttf'
    

<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'

        Image:
            source: 'assets/images/logo.jpg'
            size_hint: 1, 0.4

        Label:
            text: 'Menu Screen'
            font_size: '40sp'
            size_hint: 1, 0.2

        ButtonMenu:
            text: 'GAME'
            on_press: root.go_game()

        ButtonMenu:
            text: 'Settings'
            on_press: root.go_settings()

        ButtonMenu:
            text: 'Exit'
            on_press: rott.exit()

<RotatedImage>:
    canvas.before:
        PushMatrix
        Rotate:
            angle: self.angle
            axis: 0, 0, 1
            origin: self.center
    canvas.after:
        PopMatrix

<GameScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '10dp'

        Label:
            text: 'Score: ' + str(root.score)
            font_size: '30sp'
            size_hint: 1, 0.2

        FloatLayout:

            size_hint_y: 0.7

            Fish:
                id: fish
                size_hint: None, None
                size: 200, 200
                allow_stretch: True
                center: root.center

            Label:
                id: level_complete
                text: 'Level Complete!'
                font_size: '30sp'
                size_hint: None, None
                size: self.texture_size
                center: self.parent.center
                opacity: 0

        ButtonIcon:
            text: '\uE08A'
            on_press: root.go_menu()

<SettingsScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: '20dp'
        spacing: '20dp'

        Label:
            text: 'Settings'
            font_size: '40sp'

        ButtonMenu:
            text: 'Menu'
            on_press: root.go_menu()
